### ISSUE TITLE
Registration?

### ISSUE THREAD

**Issue by GilDev** [sunenielsen/tribaltrouble#9]
Hi,
I just learned what happened to TT, it's very sad I was a fellow player of it when I was young it gave me so much fun… Anyway, thanks for releasing the sources, however, is there like a "universal serial number" to unlock the game without touching to the sources or create databases? I'm not familiar with Java and can't put my hands in it now.
Thanks and by the way, what are the creators of TT doing right now? Did they make any new game or softwares?

**Comment by sunenielsen** [comment]
I have just committed a registration file everyone can use. You can find it in the binaries folder.

**Comment by GilDev** [comment]
Thanks a LOT!

**Comment by inukaze** [comment]
Hi there i had download the registration file and put on ~/.TribalTrouble , after i compile with "ant run", but when i run the game still show me "Buy Game" and "Register". How i can fix it ?

**Comment by veslav3** [comment]
@inukaze if nothing works, I know a guy who has been working on a remastered version. It will be a little different experience, but he has made everything to work including multiplayer. https://www.tribaltroubleremastered.com/

**Comment by inukaze** [comment]
Thanks @veslav3 , i hope that version works fine with OpenGL 1.3 too :)

**Comment by Jose123456** [comment]
If you build the game from source, you're also going to need the registration public key, which is [supposed to live in `common/static`](https://github.com/sunenielsen/tribaltrouble/blob/master/tt/build.xml#L236).

I extracted it from the `TribalTroubleSetup.sh` installer, and [placed it in `tt/static` in my repo. ](https://github.com/Jose123456/tribaltrouble/blob/fbsd-eclipse/tt/static/public_reg_key) That path is more convenient for working under Eclipse.
